const SCENE_WIDTH = 20;
const DEFAULT_HEIGHT = 800;
const GROUP_MARGIN = 50;
const PATH_SPACE = 50;
const LABEL_SIZE = [250, 15]; // TODO: Try to calculate this programatically

const ScrollDirection = Object.freeze({
	LEFT: -1,
	RIGHT: 1,
});

const VisibilityOptions = Object.freeze({
	HIDE_UNSELECTED_CHARS: 'HIDE_UNSELECTED_CHARS',
	INCLUDE_SELECTED_CHARS_IN_ALL_EVENTS: 'INCLUDE_SELECTED_CHARS_IN_ALL_EVENTS',
	HIDE_SCENES_WO_SELECTED_CHARS: 'HIDE_SCENES_WO_SELECTED_CHARS',
	HIDE_UNSELECTED_SCENES: 'HIDE_UNSELECTED_SCENES',
	HIDE_LOCATIONS: 'HIDE_LOCATIONS',
});

const NarrativeEvents = {
	CHANGE_EVENT: 'CHANGE_EVENT',
	TIME_CHANGE_EVENT: 'TIME_CHANGE_EVENT',
	CHAR_CHANGE_EVENT: 'CHAR_CHANGE_EVENT',
	CHAR_SELECT_CHANGE_EVENT: 'CHAR_SELECT_CHANGE_EVENT',
	SCENE_SELECT_CHANGE_EVENT: 'SCENE_SELECT_CHANGE_EVENT',
	ACTIVE_SCENE_CHANGE_EVENT: 'ACTIVE_SCENE_CHANGE_EVENT',
	SCROLL_TO_SCENE_EVENT: 'SCROLL_TO_SCENE_EVENT',
	LOCATION_SELECT_CHANGE_EVENT: 'LOCATION_SELECT_CHANGE_EVENT',
};

export {
	SCENE_WIDTH,
	DEFAULT_HEIGHT,
	GROUP_MARGIN,
	PATH_SPACE,
	LABEL_SIZE,
	ScrollDirection,
	VisibilityOptions,
	NarrativeEvents,
};
